### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by iam-gopi**
1. Changed the way links are opening
2. Made navbar background blur

NOTE: If you have any other ideas. You can let me know will contribute.

### CODE REVIEW

**Review by jjw24 — COMMENTED** [review]
Hi how's it going? Thank you for the PR.

With all links opening in the same browser tab, what would be the reason for opening the download and GitHub repo links in a new tab?

Also I think the navbar background blur is not showing, could you double check please.

**Comment by iam-gopi** [comment]
1. opening the link in another tab is just for visitors to not leave the parent site. I know a little SEO there is a saying called bounce ratio (I think). this helps to monetise it. 
2. I verified in Edge, Chrome both browsers support blur and its working. Mozilla alone doesn't support it in the latest version it seems and we have to manually enable it seems. I even provided a workaround for it. kindly do check it

**Comment by jjw24** [comment]
Yeah makes sense, I will take another look later :)

**Comment by Zeroto521** [comment]
Thanks for doing that. Is there a demo website? So we can have a preview.

**Comment by iam-gopi** [comment]
> Thanks for doing that. Is there a demo website? So we can have a preview.

No, haven't deployed anywhere let me try to record a small video of it and will share it here. If possible

**Comment by jjw24** [comment]
All good i got a deployment of your changes temporarily up at https://jjw24.github.io/flow-launcher.github.io/, LGTM. Thank you for the changes.

**Review by jjw24 — APPROVED** [review]

**Comment by iam-gopi** [comment]
@jjw24 thanks for merging if you would like to do any changes to the site let me know if I can able to do that. I'm also a c# based FSD I can work on .net projects too. Hope to get a call from you if you have any tasks for me. thanks again.

**Comment by jjw24** [comment]
Thank you for the offer @softwareengineerofficial, I think the website is quite alright right now although I would like it to showcase flow's features a bit more. There are some good enhancement issues in the the main flow repo if you are interested to take a stab at them that will be much appreciated as well 😄

**Pull request merged**
